### PR TITLE
Add support for modified installation paths

### PR DESCRIPTION
**Pull request by f3flight**
This is supported by `pip freeze` argument `--path`, but currently not supported by `pipdeptree`.

### CODE REVIEW

**Comment by f3flight** [comment]
@naiquevin Hi Vineet! would you have a moment to review this simple improvement?

**Comment by naiquevin** [comment]
Hi @f3flight. Thanks for the PR. It looks good on a quick glance. But I'll take some time to understand the change in more detail. I haven't been using python primarily since last few years so I am not really up-to-date with the latest developments in pip.

**Comment by f3flight** [comment]
@naiquevin sure, thanks! In short, this option allows to scan an arbitrary environment/lib folders, instead of the current.

**Review by gaborbernat — CHANGES_REQUESTED** [review]
I think the --python flag is what you're supposed to use instead of this.

**Pull request closed without merging**
