### PR TITLE
PR for issue #99 and issue #100

### PR DESCRIPTION
**Pull request by zufuliu**
PR for issue #99 and issue #100.

### CODE REVIEW

**Comment by naiquevin** [comment]
First of all, sorry for a very late reply! Finally got around to looking at the PRs on this project.

Regarding #99 : I think just making the `pkg.key` lowercase will not solve the problem because the `dump_graphviz` function is using `project_name` attribute to identify graph nodes instead of `key`.  I think a simple fix is to use `key` as the id for the graph node in the `dump_graphviz` function. It's also a "safer" solution as it won't affect rest of the code at all. 

Regarding #100 : Looks good to me.

**Comment by naiquevin** [comment]
Also, don't worry about the tests. I'm working on fixing the tests in another branch. In the meanwhile, I'll manually make sure that the tests pass before merging the PR.

**Comment by zufuliu** [comment]
OK, I will make rebase the code and make separate PRs later.

**Comment by gaborbernat** [comment]
Closing as this seems to have stalled.

**Pull request closed without merging**
