### PR TITLE
Use unicode characters when rendering text

### LINKED ISSUE #181: Consider unicode line characters to visualize the tree
This package has a nice way of displaying the tree that I think could be easier to follow than the current way `pipdeptree` works using `├──` style characters:

- https://github.com/wimglenn/johnnydep

```
name                                     summary
---------------------------------------  -------------------------------------------------
boto3                                    The AWS SDK for Python
├── botocore<1.11.0,>=1.10.77            Low-level, data-driven core of boto 3.
│   ├── docutils>=0.10                   Docutils -- Python Documentation Utilities
│   ├── jmespath<1.0.0,>=0.7.1           JSON Matching Expressions
│   └── python-dateutil<3.0.0,>=2.1      Extensions to the standard Python datetime module
│       └── six>=1.5                     Python 2 and 3 compatibility utilities
├── jmespath<1.0.0,>=0.7.1               JSON Matching Expressions
└── s3transfer<0.2.0,>=0.1.10            An Amazon S3 Transfer Manager
    └── botocore<2.0.0,>=1.3.0           Low-level, data-driven core of boto 3.
        ├── docutils>=0.10               Docutils -- Python Documentation Utilities
        ├── jmespath<1.0.0,>=0.7.1       JSON Matching Expressions
        └── python-dateutil<3.0.0,>=2.1  Extensions to the standard Python datetime module
            └── six>=1.5                 Python 2 and 3 compatibility utilities
```

### PR DESCRIPTION
**Pull request by kemzeb**
Resolves #181.

I followed the layout mentioned in this issue as well as looked at some examples in the anytree project when implementing this.

**Note that** I did have quite a battle trying to align the bullets (e.g. ├──) to be "pointing" to the first character of a dependency name, so I used the power of trial and error to observe if each bullet aligned correctly no matter how far a dependency is down its dependency tree.

I modified the `test_render_text()` to use the Unicode characters to account for my change. I also manually tested this change by looking at projects which have large dependency trees such as Scrapy, TensorFlow, and hatch to see if they will suffer any alignment issues, and from what I was able to see it produced the expected results.

Here is an example using Scrapy:
```console
(venv) ➜  pipdeptree git:(render-text-with-unicode) ✗ pipdeptree -p Scrapy       

Scrapy==2.9.0
├── cryptography [required: >=3.4.6, installed: 41.0.1]
│   └── cffi [required: >=1.12, installed: 1.15.1]
│       └── pycparser [required: Any, installed: 2.21]
├── cssselect [required: >=0.9.1, installed: 1.2.0]
├── itemadapter [required: >=0.1.0, installed: 0.8.0]
├── itemloaders [required: >=1.0.1, installed: 1.1.0]
│   ├── itemadapter [required: >=0.1.0, installed: 0.8.0]
│   ├── jmespath [required: >=0.9.5, installed: 1.0.1]
│   ├── parsel [required: >=1.5.0, installed: 1.8.1]
│   │   ├── cssselect [required: >=0.9, installed: 1.2.0]
│   │   ├── jmespath [required: Any, installed: 1.0.1]
│   │   ├── lxml [required: Any, installed: 4.9.2]
│   │   ├── packaging [required: Any, installed: 23.1]
│   │   └── w3lib [required: >=1.19.0, installed: 2.1.1]
│   └── w3lib [required: >=1.17.0, installed: 2.1.1]
├── lxml [required: >=4.3.0, installed: 4.9.2]
├── packaging [required: Any, installed: 23.1]
├── parsel [required: >=1.5.0, installed: 1.8.1]
│   ├── cssselect [required: >=0.9, installed: 1.2.0]
│   ├── jmespath [required: Any, installed: 1.0.1]
│   ├── lxml [required: Any, installed: 4.9.2]
│   ├── packaging [required: Any, installed: 23.1]
│   └── w3lib [required: >=1.19.0, installed: 2.1.1]
├── protego [required: >=0.1.15, installed: 0.2.1]
│   └── six [required: Any, installed: 1.16.0]
├── PyDispatcher [required: >=2.0.5, installed: 2.0.7]
├── pyOpenSSL [required: >=21.0.0, installed: 23.2.0]
│   └── cryptography [required: >=38.0.0,<42,!=40.0.1,!=40.0.0, installed: 41.0.1]
│       └── cffi [required: >=1.12, installed: 1.15.1]
│           └── pycparser [required: Any, installed: 2.21]
├── queuelib [required: >=1.4.2, installed: 1.6.2]
├── service-identity [required: >=18.1.0, installed: 21.1.0]
│   ├── attrs [required: >=19.1.0, installed: 23.1.0]
│   ├── cryptography [required: Any, installed: 41.0.1]
│   │   └── cffi [required: >=1.12, installed: 1.15.1]
│   │       └── pycparser [required: Any, installed: 2.21]
│   ├── pyasn1 [required: Any, installed: 0.5.0]
│   ├── pyasn1-modules [required: Any, installed: 0.3.0]
│   │   └── pyasn1 [required: >=0.4.6,<0.6.0, installed: 0.5.0]
│   └── six [required: Any, installed: 1.16.0]
├── setuptools [required: Any, installed: 65.5.0]
├── tldextract [required: Any, installed: 3.4.4]
│   ├── filelock [required: >=3.0.8, installed: 3.12.0]
│   ├── idna [required: Any, installed: 3.4]
│   ├── requests [required: >=2.1.0, installed: 2.31.0]
│   │   ├── certifi [required: >=2017.4.17, installed: 2023.5.7]
│   │   ├── charset-normalizer [required: >=2,<4, installed: 3.1.0]
│   │   ├── idna [required: >=2.5,<4, installed: 3.4]
│   │   └── urllib3 [required: >=1.21.1,<3, installed: 1.26.16]
│   └── requests-file [required: >=1.4, installed: 1.5.1]
│       ├── requests [required: >=1.0.0, installed: 2.31.0]
│       │   ├── certifi [required: >=2017.4.17, installed: 2023.5.7]
│       │   ├── charset-normalizer [required: >=2,<4, installed: 3.1.0]
│       │   ├── idna [required: >=2.5,<4, installed: 3.4]
│       │   └── urllib3 [required: >=1.21.1,<3, installed: 1.26.16]
│       └── six [required: Any, installed: 1.16.0]
├── Twisted [required: >=18.9.0, installed: 22.10.0]
│   ├── attrs [required: >=19.2.0, installed: 23.1.0]
│   ├── Automat [required: >=0.8.0, installed: 22.10.0]
│   │   ├── attrs [required: >=19.2.0, installed: 23.1.0]
│   │   └── six [required: Any, installed: 1.16.0]
│   ├── constantly [required: >=15.1, installed: 15.1.0]
│   ├── hyperlink [required: >=17.1.1, installed: 21.0.0]
│   │   └── idna [required: >=2.5, installed: 3.4]
│   ├── incremental [required: >=21.3.0, installed: 22.10.0]
│   ├── typing-extensions [required: >=3.6.5, installed: 4.6.3]
│   └── zope.interface [required: >=4.4.2, installed: 6.0]
│       └── setuptools [required: Any, installed: 65.5.0]
├── w3lib [required: >=1.17.0, installed: 2.1.1]
└── zope.interface [required: >=5.1.0, installed: 6.0]
    └── setuptools [required: Any, installed: 65.5.0]
(venv) ➜  pipdeptree git:(render-text-with-unicode) ✗ 
```

Using the freeze option:
```console
(venv) ➜  pipdeptree git:(render-text-with-unicode) ✗ pipdeptree -p Scrapy -f

Scrapy==2.9.0
cryptography==41.0.1
  cffi==1.15.1
    pycparser==2.21
cssselect==1.2.0
itemadapter==0.8.0
itemloaders==1.1.0
  itemadapter==0.8.0
  jmespath==1.0.1
  parsel==1.8.1
    cssselect==1.2.0
    jmespath==1.0.1
    lxml==4.9.2
    packaging==23.1
    w3lib==2.1.1
  w3lib==2.1.1
lxml==4.9.2
packaging==23.1
parsel==1.8.1
  cssselect==1.2.0
  jmespath==1.0.1
  lxml==4.9.2
  packaging==23.1
  w3lib==2.1.1
Protego==0.2.1
  six==1.16.0
PyDispatcher==2.0.7
pyOpenSSL==23.2.0
  cryptography==41.0.1
    cffi==1.15.1
      pycparser==2.21
queuelib==1.6.2
service-identity==21.1.0
  attrs==23.1.0
  cryptography==41.0.1
    cffi==1.15.1
      pycparser==2.21
  pyasn1==0.5.0
  pyasn1-modules==0.3.0
    pyasn1==0.5.0
  six==1.16.0
setuptools==65.5.0
tldextract==3.4.4
  filelock==3.12.0
  idna==3.4
  requests==2.31.0
    certifi==2023.5.7
    charset-normalizer==3.1.0
    idna==3.4
    urllib3==1.26.16
  requests-file==1.5.1
    requests==2.31.0
      certifi==2023.5.7
      charset-normalizer==3.1.0
      idna==3.4
      urllib3==1.26.16
    six==1.16.0
Twisted==22.10.0
  attrs==23.1.0
  Automat==22.10.0
    attrs==23.1.0
    six==1.16.0
  constantly==15.1.0
  hyperlink==21.0.0
    idna==3.4
  incremental==22.10.0
  typing_extensions==4.6.3
  zope.interface==6.0
    setuptools==65.5.0
w3lib==2.1.1
zope.interface==6.0
  setuptools==65.5.0
(venv) ➜  pipdeptree git:(render-text-with-unicode) ✗ 
```

### CODE REVIEW

**Comment by kemzeb** [comment]
The recent snapshot resolves a flake8 issue that the CI caught.

**Comment by kemzeb** [comment]
The most recent change renames a variable and rewords a comment.

**Comment by kemzeb** [comment]
Hmm I just realized that with the freeze option, a project's direct dependencies are not prefixed with spaces (look at the example I provided above). This is because without a bullet prefix, only the project name will remain for direct dependencies.

A simple fix I found would just be to add 2 spaces to the `bullet` variable, thereby not only moving the direct dependencies by 2 spaces but also their children. I'll go ahead and do that.

**Review by gaborbernat — CHANGES_REQUESTED** [review]
There needs to be a way to opt out of this behaviour when the tty does not support unicode.

**Comment by kemzeb** [comment]
Good point, though I'm not sure yet how to detect if the tty doesn't support unicode. I'll take a look into it.

One simple approach I have is that we can have `render_text()` detect unicode support. If there is, call a function that has the new changes, say `render_text_with_unicode()`, and return. Otherwise, we fallback to running the original code. I'll modify the testing code so that I can test against these two functions.

**Comment by kemzeb** [comment]
After reading the [Python docs](https://docs.python.org/3/library/sys.html#sys.stdout), I believe I can retrieve the encoding by using `sys.stdout.encoding`. The encoding is set by `PyConfig.stdio_encoding`, which would then get the [local encoding](https://docs.python.org/3/c-api/init_config.html#c.PyConfig.stdio_encoding).

**Comment by kemzeb** [comment]
I made the necessary changes using my approach, utilizing the following 3 functions: `render_text()`, `_render_text_with_unicode()`, and `_render_text_without_unicode()`. I've just been struggling for some time mocking `sys.stdout.encoding` since it is a read-only property.

**Comment by gaborbernat** [comment]
@kemzeb I don't think you pushed the code.

**Comment by kemzeb** [comment]
The most recent snapshot will have `render_text()` fallback to the original way we rendered text when we detect that unicode is not supported. It also adds the necessary Pytest params to test the old way of rendering text.

**Review by gaborbernat — APPROVED** [review]

**Comment by kemzeb** [comment]
Thanks!

**Pull request merged**
