### PR TITLE
missing README file for sdist package to be installable

### PR DESCRIPTION
**Pull request by kif**

### CODE REVIEW

**Comment by naiquevin** [comment]
Thanks. If I understand it correctly, this is required because setup.py reads `README.rst`?

**Comment by naiquevin** [comment]
Hi, the `README.rst` file is already included in the source tarball of pipdeptree ver. 0.4.3 on PyPI - https://pypi.python.org/packages/source/p/pipdeptree/pipdeptree-0.4.3.tar.gz#md5=d5ec8400f2bdfd23c91e5901ca159ee2 

What am I missing?

**Comment by kif** [comment]
On Sat, 14 Nov 2015 11:13:10 -0800
Vineet Naik <notifications@github.com> wrote:

> Hi, the `README.rst` file is already included in the source tarball of pipdeptree ver. 0.4.3 on PyPI - https://pypi.python.org/packages/source/p/pipdeptree/pipdeptree-0.4.3.tar.gz#md5=d5ec8400f2bdfd23c91e5901ca159ee2 
> 
> What am I missing?

Hi,
if you do a "python setup.py sdist" your generated "source"
distribution no more contains the README.rst file, making any further
invocation of setup.py fail.

Cheers,

J.

**Comment by naiquevin** [comment]
For me the generated source file does include the `README.rst` file. Could it be the version of setuptools? I am using `18.1`.

**Comment by gaborbernat** [comment]
This should be fixed on main.

**Pull request closed without merging**
